site_name: Teerapat Document
nav:
  - Home: index.md
  - Linux:
      - Command: linux/command.md
      - Linux Achitecturre Command: linux/structure.md
  - Airflow:
      - install: airflow/install.md
      - Configuration: airflow/configuration.md
  - Longhorn:
      - Configuration: longhorn/longhorn.md
  - Helm:
      - Configuration: helm/configuration.md
  - Kubernetes:
      - Configuration: kubernetes/kubernetes.md
  - Installation:
      - Configuration: installation/install.md
  - Docker:
      - How to use: docker/docker.md
  - CI/CD:
      - Practice: cicd/cicd.md
  - Cloudera:
      - install: cloudera/install.md
      - Configuration: cloudera/cloudera.md
docs_dir: docs

theme:
  name: material
