site_name: Teerapat Document
nav:
  - Home: index.md
  - Airflow:
      - Configuration: airflow/configuration.md
  - Longhorn:
      - Configuration: longhorn/longhorn.md
  - Helm:
      - Configuration: helm/configuration.md
  - Kubernetes:
      - Configuration: kubernetes/kubernetes.md
  - Installation:
      - Configuration: installation/install.md
  - Docker:
      - Configuration: docker/docker.md
  - CI/CD:
      - Configuration: cicd/cicd.md
  - Cloudera:
      - Configuration: cloudera/cloudera.md
docs_dir: docs

theme:
  name: material
